apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nestjs-metrics-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: nestjs-metrics
    kind: Deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50